# version: "3"

# 构建时临时使用代理的方法
# fq_host=the_ip_address_of_host:7890
# 以下二选一
# docker compose build --build-arg HTTP_PROXY=http://$fq_host --build-arg HTTPS_PROXY=http://$fq_host  --build-arg ALL_PROXY=socks5://$fq_host --no-cache
# 或者
# docker compose build --build-arg ALL_PROXY=socks5://$fq_host --no-cache

# official repo URL=https://github.com/qbittorrent/docker-qbittorrent-nox
services:
  qbittorrent_nox:
    extends:
      # file: ./docker-compose.official.example.yml
      file: ./docker-compose.linuxserver.example.yml
      service: qbittorrent_nox
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    ports:
      - "127.0.0.1:28012:28012"
      # BT connection port (MUST be the same as the env var "TORRENTING_PORT")
      - "55285:55285"
      - "55285:55285/udp"
