# version: "3"

# official repo URL=https://github.com/linuxserver/docker-qbittorrent
services:
  qbittorrent_nox:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: ./default_linuxserver.env
        required: true # default
      - path: /mnt/justsave/docker/env/qbittorrent_nox/docker.env
        required: false
    container_name: qbittorrent-nox
    image: linuxserver/qbittorrent:latest
    pull_policy: always
    # for debugging
    cap_add:
      - SYS_PTRACE
    # read_only: true
    stop_grace_period: 30m
    # tmpfs:
    #   - /tmp
    tty: true
    volumes:
      # 数据持久化
      - /mnt/justsave/docker/volume/qbittorrent_nox:/mnt/justsave/docker/volume/qbittorrent_nox
      - /mnt/justsave/docker/volume/qbittorrent_nox/linuxserver/config:/config
      - /mnt/justsave/docker/volume/qbittorrent_nox/downloads:/downloads
      - /mnt/justsave/BT:/mnt/justsave/BT
      - /mnt/justsave/PT:/mnt/justsave/PT
    # restart: always
    # restart: "no"
    restart: unless-stopped
