function getIsoTime(r) {
    // var date = new Date();
    // var year = date.getFullYear();
    // var month = ("0" + (date.getMonth() + 1)).slice(-2);
    // var day = ("0" + date.getDate()).slice(-2);
    // var hours = ("0" + date.getHours()).slice(-2);
    // var minutes = ("0" + date.getMinutes()).slice(-2);
    // var seconds = ("0" + date.getSeconds()).slice(-2);

    // var serverTime = `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
    // r.return(200, "Server time: " + serverTime + "\n");
    
    // const now = new Date();
    // const options = {
    //   timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    // //   timeZone: "Asia/Hong_kong",
    //   hour12: false, // 使用24小时制
    //   year: 'numeric',
    //   month: '2-digit',
    //   day: '2-digit',
    //   hour: '2-digit',
    //   minute: '2-digit',
    //   second: '2-digit'
    // };
    // const formatter = new Intl.DateTimeFormat('zh-CN', options);
    // r.return(200, "Server time: " + formatter.format(now) + "\n");

    
    // r.return(200, "Server time: " + (new Date()).toISOString() + "\n");
    // r.return(200, (new Date()).toISOString());
    return (new Date()).toISOString();
}

// Generated by AI Alibaba Tongyi
function getLocalIsoTime(r) {
    // 获取当前时间
    let now = new Date();

    // 获取本地时区偏移量（分钟）
    let offsetMinutes = now.getTimezoneOffset();

    // 计算本地时间
    let localTime = new Date(now.getTime() - offsetMinutes * 60000);

    // 格式化为 ISO 时间
    let isoTime = localTime.toISOString().slice(0, -1); // 去掉末尾的 'Z'

    // 获取时区偏移量（小时和分钟）
    let offsetHours = Math.floor(Math.abs(offsetMinutes) / 60);
    let offsetMinutesRemaining = Math.abs(offsetMinutes) % 60;
    let offsetSign = offsetMinutes > 0 ? '-' : '+';
    let offset = `${offsetSign}${String(offsetHours).padStart(2, '0')}:${String(offsetMinutesRemaining).padStart(2, '0')}`;

    // 返回格式化后的本地时间
    return `${isoTime}${offset}`;
}

const getLocaleTime = (r) => (new Date()).toLocaleTimeString();

export default {
    getIsoTime,
    getLocalIsoTime,
    getLocaleTime
};
