services:
  ttyd:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: ttyd
    logging:
      options:
        max-size: 4m
    networks:
      my_docker_network: {}

include:
  - ../../docker-compose.preset.network.yml
