# version: "3.8"

# official repo URL=https://github.com/tsl0922/ttyd
services:
  ttyd:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/ttyd/docker.env
        required: false
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "cc.xfl12345.code.share.docker.setup.localbuild=true"
    container_name: ttyd
    # image: tsl0922/ttyd:alpine
    image: tsl0922/ttyd:alpine-xfl
    pull_policy: build
    build:
      context: ./
      additional_contexts:
        resources: /mnt/justsave/docker/compose/build_resource
      dockerfile: ttyd-xfl.Dockerfile
      pull: true
    # command: "ttyd --writable --ipv6 --port 28041 bash"
    volumes:
      # 持久化
      - /mnt/justsave/docker/volume/ttyd/home:/home/ttyd
      # socket 通信
      - /var/run/ttyd:/var/run/ttyd
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

# Nginx 
