# version: "3"
services:
  ubuntu4build:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /media/justsave/docker/env/ubuntu4build/docker.env
        required: false
    container_name: ubuntu4build
    image: ubuntu4build
    pull_policy: build
    build:
      context: ./
      dockerfile: ubuntu.Dockerfile
      pull: true
    restart: always
