# version: "3"
services:
  ubuntu4build:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/ubuntu4build/docker.env
        required: false
    image: ubuntu4build
    container_name: ubuntu4build
    pull_policy: build
    build:
      context: ./
      dockerfile: ubuntu.Dockerfile
      pull: true
    extra_hosts:
      - host.docker.internal:host-gateway
    network_mode: bridge
    ports:
      - 24023:22
    restart: always
