services:
  ubuntu4build:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: ubuntu4build
    extra_hosts:
      - host.docker.internal:host-gateway
    network_mode: bridge
    ports:
      - 24023:22
