services:
  neko:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: neko
    logging:
      options:
        max-size: 4m
    shm_size: 1gb
    privileged: true
    networks:
      my_docker_network: {}
    ports:
      - 127.0.0.1:28044:8080
      - 127.0.0.1:28044:8080/udp
      - 52000-52100:52000-52100/udp

include:
  - ../../docker-compose.preset.network.yml
