services:
  xray:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: xray
    logging:
      options:
        max-size: 4m
    volumes:
      # xtls/xray unix socket
      - /var/run/xray:/var/run/xray
    network_mode: host
