# version: '3'

# source code URL=https://github.com/netdata/netdata/blob/master/packaging/docker/README.md
# official repo URL=https://github.com/netdata/netdata
services:
  netdata:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/netdata/docker.env
        required: false
    pid: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    image: netdata/netdata:latest
    container_name: netdata
    volumes:
      - /mnt/justsave/docker/volume/netdata/config:/etc/netdata
      # 如需自定义，请自行添加映射 /mnt/justsave/docker/volume/netdata/config/netdata.conf:/etc/netdata/netdata.conf
      - ./netdata.example.conf:/etc/netdata/netdata.conf
      - /mnt/justsave/docker/volume/netdata/lib:/var/lib/netdata
      - /mnt/justsave/docker/volume/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: 4m
    network_mode: host
    restart: unless-stopped
