# version: "3"

# official repo URL=https://github.com/linuxserver/docker-transmission
# official docs URL=https://docs.linuxserver.io/images/docker-transmission/
services:
  transmission:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/transmission/docker.env
        required: false
    image: linuxserver/transmission:latest
    container_name: transmission
    pull_policy: always
    volumes:
      # 持久化
      - /mnt/justsave/docker/volume/default/transmission/moved_root/config:/config
      - /mnt/justsave/docker/volume/default/transmission/moved_root/downloads:/downloads
      - /mnt/justsave/docker/volume/default/transmission/moved_root/watch:/watch
      # BT客户端专享目录
      - /mnt/justsave/BT:/mnt/justsave/BT
      - /mnt/justsave/PT:/mnt/justsave/PT
    logging:
      options:
        max-size: 4m
    network_mode: host
    restart: unless-stopped
