# version: "3"

# official repo URL=https://github.com/jeessy2/ddns-go
services:
  ddns_go:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - cc.xfl12345.code.share.docker.setup.localbuild=true
    image: localbuild/ddns-go
    container_name: ddns-go
    pull_policy: build
    build:
      context: ./
      dockerfile_inline: |
        FROM jeessy/ddns-go:latest
        RUN apk update
        RUN apk add bind-tools
      pull: true
    volumes:
      - /mnt/justsave/docker/volume/ddns_go:/root:rw
    command: -l 127.0.0.1:9876 -f 10
    logging:
      options:
        max-size: 4m
    network_mode: host
    restart: always
