# version: "3"

# official repo URL=https://github.com/jeessy2/ddns-go
services:
  ddns_go:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "cc.xfl12345.code.share.docker.setup.localbuild=true"
    container_name: ddns-go
    image: jeessy/ddns-go:latest-xfl
    pull_policy: build
    build:
      context: ./
      dockerfile_inline: |
        FROM jeessy/ddns-go:latest
        RUN apk update
        RUN apk add bind-tools
      pull: true
    volumes:
      - /media/justsave/docker/volume/ddns_go:/root:rw
    command: -l 127.0.0.1:9876 -f 10
    restart: always
