# version: "3"

# official repo URL=https://github.com/apache/hertzbeat
# official docs URL=https://hertzbeat.apache.org/docs/start/docker-deploy/
services:
  hertzbeat:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: /mnt/justsave/docker/env/default/hertzbeat/docker.env
        required: false
    image: apache/hertzbeat:latest
    container_name: hertzbeat
    pull_policy: always
    volumes:
      - /mnt/justsave/docker/volume/default/hertzbeat/moved_root/opt/hertzbeat/data:/opt/hertzbeat/data
      - /mnt/justsave/docker/volume/default/hertzbeat/moved_root/opt/hertzbeat/logs:/opt/hertzbeat/logs
      - /mnt/justsave/docker/volume/default/hertzbeat/moved_root/opt/hertzbeat/ext-lib:/opt/hertzbeat/ext-lib
      - /mnt/justsave/docker/volume/default/hertzbeat/moved_root/opt/hertzbeat/config/application.yml:/opt/hertzbeat/config/application.yml
      - /mnt/justsave/docker/volume/default/hertzbeat/moved_root/opt/hertzbeat/config/sureness.yml:/opt/hertzbeat/config/sureness.yml
    logging:
      options:
        max-size: 4m
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - hertzbeat_docker_bridge
    ports:
      - 127.0.0.1:28018:1157
      - 127.0.0.1:1158:1158
    depends_on:
      - hertzbeat_docker_socket_relay
    restart: always

  hertzbeat_docker_socket_relay:
    image: alpine/socat:latest
    container_name: hertzbeat-docker-socket-relay
    volumes:
      # 挂载 docker socket ，直通宿主机
      - /var/run/docker.sock:/var/run/docker.sock
    command: -d2 tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    logging:
      options:
        max-size: 4m
    networks:
      - hertzbeat_docker_bridge
    restart: always

include:
  - ./docker-compose.network.yml
