# version: "3"

# official repo URL=https://github.com/jenkinsci/docker
# official docs URL=https://www.jenkins.io/doc/book/installing/docker/
services:
  jenkins:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/jenkins/docker.env
        required: false
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - cc.xfl12345.code.share.docker.setup.localbuild=true
    security_opt:
      - apparmor=unconfined
    # image: jenkins/jenkins:lts-jdk17 # jenkinsci/blueocean 镜像仅支持 amd64 架构，故ARM架构主机不能使用。如果执意使用会产生性能问题和其它奇怪的问题。
    image: localbuild/jenkins
    container_name: jenkins
    pull_policy: build
    build:
      context: ./
      additional_contexts:
        resources: /mnt/justsave/docker/compose/build_resource
      dockerfile: jenkins.Dockerfile
      pull: true
      args:
        - BASE_IMAGE_TAG
    volumes:
      # 持久化
      - /mnt/justsave/docker/volume/jenkins:/var/jenkins_home
      # 带环境进入容器 bash 的小工具
      - ./just_bash.sh:/usr/local/bin/just_bash.sh
      # # 挂载 docker socket ，直通宿主机
      # - /usr/bin/docker:/usr/bin/docker:ro
      # - /var/run/docker.sock:/var/run/docker.sock:rw
      # # 共享host的时间环境
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      # 共享host的GNU库
      # - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:ro
      # - /usr/lib/arm-linux-gnu:/usr/lib/arm-linux-gnu:ro
      # - /usr/lib/arm-linux-gnueabi:/usr/lib/arm-linux-gnueabi:ro
      # - /usr/lib/arm-linux-gnueabihf:/usr/lib/arm-linux-gnueabihf:ro
      # - /usr/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:ro
      # - /usr/lib/mips64el-linux-gnuabi64:/usr/lib/mips64el-linux-gnuabi64:ro
      # - /usr/lib/mips64-linux-gnuabi64:/usr/lib/mips64-linux-gnuabi64:ro
      # - /usr/lib/mipsel-linux-gnu:/usr/lib/mipsel-linux-gnu:ro
      # - /usr/lib/mipsisa32r6el-linux-gnu:/usr/lib/mipsisa32r6el-linux-gnu:ro
      # - /usr/lib/mipsisa64r6el-linux-gnuabi64:/usr/lib/mipsisa64r6el-linux-gnuabi64:ro
      # - /usr/lib/mipsisa32r6-linux-gnu:/usr/lib/mipsisa32r6-linux-gnu:ro
      # - /usr/lib/mipsisa64r6-linux-gnuabi64:/usr/lib/mipsisa64r6-linux-gnuabi64:ro
      # - /usr/lib/mips-linux-gnu:/usr/lib/mips-linux-gnu:ro
      # - /usr/lib/s390x-linux-gnu:/usr/lib/s390x-linux-gnu:ro
      # - /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:ro
      # - /usr/lib/x86_64-linux-gnux32:/usr/lib/x86_64-linux-gnux32:ro
    logging:
      options:
        max-size: 4m
    hostname: jenkins
    extra_hosts:
      - host.docker.internal:host-gateway
    network_mode: bridge
    ports:
      - 127.0.0.1:28011:8080
      - 127.0.0.1:28011:8080/udp
      - 50000:50000
      - 50000:50000/udp
    restart: always

# docker run --name jenkins -p 7080:8080 -p 50000:50000 -v /etc/timezone:/etc/timezone -v /etc/localtime:/etc/localtime -v /var/docker_data/jenkins/jenkins_home:/var/jenkins_home -v /var/docker_data/jenkins/settings:/var/settings -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker -d my-jenkins
