# official repo URL=https://github.com/xfl12345/docker-setup
services:
  docker_setup:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/default/docker_setup/docker.env
        required: false
    labels:
      - com.centurylinklabs.watchtower.enable=false
    image: docker_setup
    container_name: docker-setup
    pull_policy: build
    build:
      context: ./
      additional_contexts:
        resources: /mnt/justsave/docker/compose/build_resource
      dockerfile: xfl.Dockerfile
      pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/justsave/docker/compose:/mnt/justsave/docker/compose
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    restart: no
