services:
  docker_setup:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: docker_setup
    networks:
      my_docker_network: {}

include:
  - ./docker-compose.network.yml
