# version: "3"

# official docs URL=http://wiki-zh.bitcomet.com/linux%E7%89%88bitcomet%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97
# official docs URL 2=https://hub.docker.com/r/wxhere/bitcomet
services:
  bitcomet:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: /mnt/justsave/docker/env/bitcomet/docker.env
        required: false
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - cc.xfl12345.code.share.docker.setup.localbuild=true
    sysctls:
      # - net.ipv6.conf.default.disable_ipv6=0
      # - net.ipv6.conf.default.autoconf=1
      # - net.ipv6.conf.lo.disable_ipv6=0
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.accept_ra=2
      - net.ipv6.conf.all.proxy_ndp=1
      - net.ipv6.conf.all.autoconf=1
    image: localbuild/bitcomet
    container_name: bitcomet
    pull_policy: build
    build:
      context: ./
      dockerfile_inline: |
        FROM wxhere/bitcomet:latest
        RUN apt update && apt upgrade -y
        RUN apt install -y locales locales-all at-spi2-core
      pull: true
    volumes:
      - /mnt/justsave/docker/volume/default/bitcomet/moved_root/home/sandbox/.config/BitComet:/home/sandbox/.config/BitComet
      - /mnt/justsave/docker/volume/default/bitcomet/moved_root/home/sandbox/share:/home/sandbox/share
      - ./my_entrypoint.sh:/my_entrypoint.sh
    entrypoint: [/my_entrypoint.sh]
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    ports:
      # Web GUI client port
      - 127.0.0.1:28043:80
      # Web API port
      - 127.0.0.1:28050:28050
      # VNC GUI client port
      - 127.0.0.1:55900:5900
      # 以下配置不可或缺，需自行决定！！！
      # BT connection
      - 6882:6882
      - 6882:6882/udp
    restart: always
