services:
  headscale:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: headscale
    logging:
      options:
        max-size: 4m
    ports:
      # - "8090:8090"
      - 127.0.0.1:28015:8080
      # - 0.0.0.0:9090:9090
      - 3478:3478/udp

  headscale_webui:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: headscale_webui
    logging:
      options:
        max-size: 4m
    ports:
      - 127.0.0.1:28016:8080

  tailscale_client:
    extends:
      file: ../tailscale/docker-compose.example.yml
      service: tailscale_client
    # depends_on:
    #   - headscale
    #   - headscale_webui
include:
  - ./docker-compose.network.yml
