# version: "3"
services:
  # official repo URL=https://github.com/juanfont/headscale
  # official docs URL=https://headscale.net/running-headscale-container/
  headscale:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.accept_ra=2
      - net.ipv6.conf.all.proxy_ndp=1
      - net.ipv6.conf.all.autoconf=1
    image: headscale/headscale:0.23.0
    container_name: headscale
    pull_policy: always
    volumes:
      - /mnt/justsave/docker/volume/default/headscale/moved_root/var/lib/headscale:/var/lib/headscale
      - /mnt/justsave/docker/volume/default/headscale/moved_root/etc/headscale:/etc/headscale
      - /var/run/headscale:/var/run/headscale
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: serve
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    ports:
      # - "8090:8090"
      - 127.0.0.1:28015:8080
      # - 0.0.0.0:9090:9090
      - 3478:3478/udp
    restart: unless-stopped


  # official repo URL=https://github.com/gurucomputing/headscale-ui
  headscale_webui:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default_headscale_webui.env
        required: true # default
      - path: /mnt/justsave/docker/env/default/headscale/headscale-webui.env
        required: false
    user: '1000'
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-webui
    pull_policy: always
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    ports:
      - 127.0.0.1:28016:8080
    restart: unless-stopped
