# version: "3"

# official docs URL=https://github.com/docker-library/docs/blob/master/php/README.md
services:
  php_fpm:
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - cc.xfl12345.code.share.docker.setup.localbuild=true
    # image: php:8.3.3-fpm-bookworm
    image: localbuild/php-fpm
    container_name: php-fpm
    pull_policy: build
    build:
      context: ./
      dockerfile: php-fpm.Dockerfile
      pull: true
    volumes:
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # nginx conf file
      - /mnt/justsave/docker/volume/default/nginx/moved_root/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # nginx vhost
      - /mnt/justsave/docker/volume/default/nginx/moved_root/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      # nginx snippets
      - /mnt/justsave/docker/volume/default/nginx/moved_root/etc/nginx/snippets:/etc/nginx/snippets:ro
      # nginx ssl cert
      - /mnt/justsave/docker/volume/default/nginx/moved_root/etc/nginx/ssl:/etc/nginx/ssl:ro
      # nginx web root
      - /mnt/justsave/wwwroot:/mnt/justsave/wwwroot:ro
      - /mnt/justsave/wwwroot/phpmyadmin:/mnt/justsave/wwwroot/phpmyadmin:rw
      # - /mnt/justsave/wwwroot/default:/var/www/html:ro
      - /mnt/justsave/BT:/mnt/justsave/BT:ro
      - /mnt/justsave/PT:/mnt/justsave/PT:ro
      - /etc/apt:/etc/apt:ro
      - /usr/share/keyrings:/usr/share/keyrings:ro
      - /mnt:/mnt:ro
      # nginx log
      - /mnt/justsave/wwwlogs:/mnt/justsave/wwwlogs
      # php-fpm unix socket
      - /var/run/php:/var/run/php
      # mysql unix socket
      - /var/run/mysqld:/var/run/mysqld
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
    logging:
      options:
        max-size: 4m
    network_mode: host
    restart: always
