services:
  peerbanhelper:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: peerbanhelper
    logging:
      options:
        max-size: 4m
    networks:
      my_docker_network: {}
    ports:
      - 127.0.0.1:28048:9898
    restart: unless-stopped

include:
  - ../../docker-compose.preset.network.yml
