# version: "3"

# official docs URL=https://jfrog.com/help/r/jfrog-installation-setup-documentation/install-artifactory-single-node-with-docker
services:
  jfrog_artifactory_oss:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
      - path: ./default_jfrog_artifactory_oss.env
        required: true # default
      - path: /media/justsave/docker/env/jfrog/artifactory/oss/docker.env
        required: false
    container_name: jfrog-artifactory-oss
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    pull_policy: always
    volumes:
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # 持久化
      # See https://jfrog.com/help/r/jfrog-installation-setup-documentation/generic-directory-layout
      # https://jfrog.com/help/r/jfrog-installation-setup-documentation/jfrog-home
      # 需要手动完成一些初始化 
      - /media/justsave/docker/volume/jfrog/artifactory/oss/fs/var/opt/jfrog/artifactory:/var/opt/jfrog/artifactory
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
