services:
  phpmyadmin:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: phpmyadmin
    logging:
      options:
        max-size: 4m
    networks:
      my_docker_network: {}
    ports:
      - 127.0.0.1:28009:80

include:
  - ../../docker-compose.preset.network.yml
