# version: "3"
services:
  debian4build:
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - cc.xfl12345.code.share.docker.setup.localbuild=true
    image: localbuild/debian4build
    container_name: debian4build
    pull_policy: build
    build:
      context: ./
      dockerfile: bookworm.Dockerfile
      pull: true
    devices:
      - /dev/mem:/dev/mem
      # - /dev/gpiochip0:/dev/gpiochip0
      # - /dev/gpiochip1:/dev/gpiochip1
      # - /dev/gpiochip2:/dev/gpiochip2
      # - /dev/gpiochip3:/dev/gpiochip3
      # - /dev/gpiochip4:/dev/gpiochip4
    # volumes:
    #   - /dev/gpiochip0:/dev/gpiochip0
    #   - /dev/gpiochip1:/dev/gpiochip1
    #   - /dev/gpiochip2:/dev/gpiochip2
    #   - /dev/gpiochip3:/dev/gpiochip3
    #   - /dev/gpiochip4:/dev/gpiochip4
    volumes:
      - /mnt/justsave/docker/compose/build_resource/infinite_sleep_loop.sh:/infinite_sleep_loop.sh
    command: /infinite_sleep_loop.sh
    network_mode: bridge
    restart: no
