services:
  wgcf:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: wgcf
    logging:
      options:
        max-size: 4m
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - http_proxy=http://host.docker.internal:7890
      - https_proxy=http://host.docker.internal:7890
      - all_proxy=socks5://host.docker.internal:7890
    networks:
      my_docker_network: {}

include:
  - ../../docker-compose.preset.network.yml
