services:
  wgcf:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: wgcf
    logging:
      options:
        max-size: 4m
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      my_docker_network: {}

include:
  - ../../docker-compose.preset.network.yml
