# version: "3"

# official repo URL=https://github.com/Neilpang/wgcf-docker
services:
  wgcf:
    container_name: wgcf
    image: neilpang/wgcf-docker:latest
    sysctls:
      # - net.ipv6.conf.default.disable_ipv6=0
      # - net.ipv6.conf.default.autoconf=1
      # - net.ipv6.conf.lo.disable_ipv6=0
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.accept_ra=2
      - net.ipv6.conf.all.proxy_ndp=1
      - net.ipv6.conf.all.autoconf=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules:ro
      - /media/justsave/docker/volume/wgcf:/wgcf
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
