# version: "3"
services:
  # official repo URL=https://github.com/MetaCubeX/mihomo
  # official docs URL=https://wiki.metacubex.one/
  clash:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    container_name: clash-meta
    image: metacubex/mihomo:v1.18.6    # 最新版用 metacubex/mihomo:Alpha
    pull_policy: always
    restart: always
    # user: "2002"
    pid: host
    ipc: host
    cap_add:
      - ALL
    security_opt:
      - apparmor=unconfined
    volumes:
      - /media/justsave/docker/volume/clash_meta/clash:/root/.config/mihomo
      - /dev/net/tun:/dev/net/tun

  # official repo URL=https://github.com/MetaCubeX/metacubexd
  metacubexd:
    container_name: metacubexd
    image: ghcr.io/metacubex/metacubexd:latest
    pull_policy: always
    restart: always
    user: "2002"
    volumes:
      - /media/justsave/docker/volume/clash_meta/caddy:/config/caddy
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
