services:
  clash:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: clash
    logging:
      options:
        max-size: 4m
    network_mode: host

  metacubexd:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: metacubexd
    logging:
      options:
        max-size: 4m
    ports:
      - 127.0.0.1:28002:80
    networks:
      my_docker_network: {}

include:
  - ../../docker-compose-default-bridge-network.yml
