services:
  gitea:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: gitea
    logging:
      options:
        max-size: 4m
    networks:
      my_docker_network: {}
    ports:
      - 127.0.0.1:28014:3000
      - 22014:22

  gitea_runner:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: gitea_runner
    logging:
      options:
        max-size: 4m
    networks:
      my_docker_network: {}

include:
  - ../../docker-compose-default-bridge-network.yml
