# version: "3"

# official docs URL=https://github.com/docker-library/docs/blob/master/nginx/README.md
services:
  nginx:
    labels:
      - com.centurylinklabs.watchtower.enable=false
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    image: nginx:latest
    container_name: nginx
    pull_policy: always
    tmpfs:
      - /var/cache/nginx
    volumes:
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # nginx conf file
      - /mnt/justsave/docker/volume/example/nginx/moved_root/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # nginx vhost
      - /mnt/justsave/docker/volume/default/nginx/moved_root/etc/nginx/conf.d:/etc/nginx/conf.d
      - /mnt/justsave/docker/volume/example/nginx/moved_root/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      # nginx snippets
      - /mnt/justsave/docker/volume/default/nginx/moved_root/etc/nginx/snippets:/etc/nginx/snippets
      - /mnt/justsave/docker/volume/example/nginx/moved_root/etc/nginx/snippets/example:/etc/nginx/snippets/example:ro
      # nginx ssl cert
      - /mnt/justsave/docker/volume/default/nginx/moved_root/etc/nginx/ssl:/etc/nginx/ssl:ro
      # openssl dhparam
      - /mnt/justsave/docker/volume/default/nginx/moved_root/etc/ssl/dhparam:/etc/ssl/dhparam
      # apache htpasswd file
      - /mnt/justsave/docker/volume/default/nginx/moved_root/etc/nginx/htpasswd:/etc/nginx/htpasswd:ro
      # nginx geoip
      - /mnt/justsave/docker/volume/default/nginx/moved_root/etc/nginx/geoip:/etc/nginx/geoip
      # GEOIP is not usable
      # # pre-prepared GeoIP file for geoip support
      # # Downloaded from https://github.com/Loyalsoldier/geoip/raw/af44001d23a7ce53e0594b304228822d95a1c317/GeoLite2-Country.mmdb
      # - ./geoip:/etc/nginx/geoip/example:ro
      # nginx web root
      - /mnt/justsave/docker/volume/default/nginx/moved_root/usr/share/nginx:/usr/share/nginx:ro
      # nginx log
      - /mnt/justsave/docker/volume/default/nginx/moved_root/var/log/nginx:/var/log/nginx
      # nginx init
      - ./05-just-init.sh:/docker-entrypoint.d/05-just-init.sh
    logging:
      options:
        max-size: 4m
    network_mode: host
    restart: always
