services:
  code_server:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: code_server
    logging:
      options:
        max-size: 4m
    networks:
      my_docker_network: {}
    ports:
      - 127.0.0.1:28042:8080

include:
  - ../../docker-compose.preset.network.yml
