# version: '3'

# official repo URL=https://github.com/nicolargo/glances
services:
  glances:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/glances/docker.env
        required: false
    container_name: glances
    image: nicolargo/glances:latest-full
    pull_policy: always
    pid: host
    ipc: host
    cap_add:
      - ALL
    security_opt:
      - apparmor=unconfined
    volumes:
      # 持久化
      - /mnt/justsave/docker/volume/glances/local_config:/root/.config/glances
      - /mnt/justsave/docker/volume/glances/global_config:/etc/glances:ro
      # 挂载 docker socket ，直通宿主机
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always