# version: "3"
services:
  ubuntu_test:
    container_name: ubuntu-test
    image: ubuntu:24.04
    pull_policy: always
    restart: "no"
    command: /infinite_sleep_loop.sh
    volumes:
      - /media/justsave/docker/compose/build_resource/infinite_sleep_loop.sh:/infinite_sleep_loop.sh

# 强行停机方法
# docker compose down --timeout 1
