services:
  ubuntu_test:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: ubuntu_test
    networks:
      my_docker_network: {}

include:
  - ../../docker-compose.preset.network.yml
