# version: "3"

# docker image source code repo URL=https://github.com/yrzr/gitlab-ce-arm64v8-docker
services:
  gitlab:
    build:
      args:
        - BASE_IMAGE_TAG=yrzr/gitlab-ce-arm64v8:16.10.1-ce.0
