services:
  fping:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /media/justsave/docker/env/fping/docker.env
        required: false
    image: localbuild-fping
    container_name: fping
    pull_policy: build
    build: 
      args:
        - PING_NET
      context: ./
      additional_contexts:
        resources: /media/justsave/docker/compose/build_resource
      dockerfile: ./fping.Dockerfile
      pull: true
