# version: "3"

# source code URL=https://github.com/wg-easy/wg-easy/blob/master/docker-compose.yml
services:
  wg_easy:
    env_file:
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/wg_easy/docker.env
        required: true
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:latest
    pull_policy: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /mnt/justsave/docker/volume/wg_easy/data/etc/wireguard:/etc/wireguard
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
