services:
  wg_easy:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: wg_easy
    logging:
      options:
        max-size: 4m
    networks:
      my_docker_network: {}
    ports:
      - 51820:51820/udp
      - 127.0.0.1:28017:28017/tcp

include:
  - ../../docker-compose.preset.network.yml
