# version: "3"

# source code URL=https://github.com/wg-easy/wg-easy/blob/master/docker-compose.yml
services:
  wg_easy:
    env_file:
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/wg_easy/docker.env
        required: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    pull_policy: always
    volumes:
      - /mnt/justsave/docker/volume/default/wg_easy/moved_root/etc/wireguard:/etc/wireguard
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    ports:
      - 51820:51820/udp
      - 127.0.0.1:28017:28017/tcp
    restart: unless-stopped

