# version: "3"
services:
  xfl_cv_javaweb:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/xfl_cv_javaweb/docker.env
        required: false
    labels:
      - com.centurylinklabs.watchtower.enable=false
    user: '1000'
    image: curriculum-vitae-web-server
    container_name: xfl-cv-javaweb
    pull_policy: never
    volumes:
      # # 共享host的时间环境
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      # 持久化
      - /mnt/justsave/docker/volume/default/xfl_cv_javaweb/moved_root/app/config:/app/config
      - /mnt/justsave/docker/volume/default/xfl_cv_javaweb/moved_root/home/xfl/logs:/home/xfl/logs
    logging:
      options:
        max-size: 4m
    extra_hosts:
      - host.docker.internal:host-gateway
    network_mode: bridge
    ports:
      - 127.0.0.1:28010:8880
    restart: unless-stopped

