services:
  puter:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: puter
    logging:
      options:
        max-size: 4m
    networks:
      my_docker_network: {}
    ports:
      - 4100:4100

include:
  - ../../docker-compose-default-bridge-network.yml
