# version: "3.4"

# source code URL=https://github.com/gravitl/netmaker/blob/master/compose/docker-compose.yml
services:

  netclient:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    container_name: netclient
    image: gravitl/netclient:v0.26.0
    # privileged: true
    pid: host
    ipc: host
    cap_add:
      - ALL
    security_opt:
      - apparmor=unconfined
    restart: always

  netmaker:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default_netmaker.env
        required: true # default
    container_name: netmaker
    image: gravitl/netmaker:v0.26.0
    networks:
      - netmaker-docker-bridge
    ports:
      - "127.0.0.1:28031:8081"
    restart: always

  netmaker_ui:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
    container_name: netmaker-ui
    image: gravitl/netmaker-ui:v0.26.0
    # environment:
    #   # config-dependant vars
    #   # URL where UI will send API requests. Change based on SERVER_HOST, SERVER_HTTP_HOST, and API_PORT
    #   BACKEND_URL: "https://api.example.com"
    networks:
      - netmaker-docker-bridge
    ports:
      - "127.0.0.1:28030:80"
    links:
      - "netmaker:api"
    restart: always

  # caddy:
  #   image: caddy:2.6.2
  #   container_name: caddy
  #   env_file: /mnt/justsave/docker/env/netmaker/cloudflare/netmaker.env
  #   restart: unless-stopped
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     # storage for Caddy
  #     - /mnt/justsave/docker/volume/netmaker/cloudflare/caddy/data:/data
  #     - /mnt/justsave/docker/volume/netmaker/cloudflare/caddy/conf:/config
  #   networks:
  #     - netmaker-docker-bridge
  #   ports:
  #     - "80:80"
  #     - "443:443"

  coredns:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
    #network_mode: host
    container_name: coredns
    image: coredns/coredns:1.10.1
    command: -conf /root/dnsconfig/Corefile
    restart: always
    networks:
      - netmaker-docker-bridge
    ports:
      - "127.0.0.1:5554:53/udp"

  mq:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
    container_name: mq
    image: eclipse-mosquitto:2.0.15-openssl
    restart: unless-stopped
    command: [ "/mosquitto/config/wait.sh" ]
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./wait.sh:/mosquitto/config/wait.sh
    networks:
      - netmaker-docker-bridge
    ports:
      - "127.0.0.1:28033:8883"

# networks:
#   netmaker-docker-bridge:
#     name: "netmaker-docker-bridge"
#     driver: bridge
#     enable_ipv6: true
#     ipam:
#       config:
#         - subnet: "172.20.1.0/24"
#           gateway: "172.20.1.1"
#           ip_range: "172.20.1.0/24"
#         - subnet: "fd00:dcdc:1::/64"
#     driver_opts:
#       com.docker.network.bridge.name: "br-netmaker0"
