# version: "3"

# official repo URL=https://github.com/containrrr/watchtower
# official docs URL=https://containrrr.dev/watchtower/
services:
  watchtower:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: /mnt/justsave/docker/env/default/watchtower/docker.env
        required: false
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    restart: unless-stopped
