services:
  portainer:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: portainer
    logging:
      options:
        max-size: 4m
    networks:
      my_docker_network: {}
    ports:
      # - 9443:9443
      - 127.0.0.1:28019:9000
      # - 8000:8000

include:
  - ../../docker-compose.preset.network.yml
