# official repo URL=https://github.com/linuxserver/docker-libreoffice
services:
  libreoffice:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/default/libreoffice/docker.env
        required: false
    privileged: true
    security_opt:
      - seccomp:unconfined #optional
    image: linuxserver/libreoffice:latest
    container_name: libreoffice
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/justsave/docker/volume/default/libreoffice/moved_root/config:/config
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    ports:
      - 127.0.0.1:28045:3000
    restart: always

