# official repo URL=https://github.com/linuxserver/docker-libreoffice
services:
  libreoffice:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: libreoffice
    logging:
      options:
        max-size: 4m
    privileged: true
    security_opt:
      - seccomp:unconfined #optional
    devices:
      - /dev/dri:/dev/dri
    networks:
      my_docker_network: {}
    ports:
      - 127.0.0.1:28045:3000

include:
  - ../../docker-compose-default-bridge-network.yml
