services:
  mariadb:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: mariadb
    logging:
      options:
        max-size: 4m
    ports:
      - 0.0.0.0:3306:3306
      - 0.0.0.0:3306:3306/udp
    networks:
      my_docker_network: {}

include:
  - ../../docker-compose-default-bridge-network.yml
