# version: "3"

# official repo URL=https://github.com/MariaDB/mariadb-docker
# official docs URL=https://mariadb.com/kb/en/installing-and-using-mariadb-via-docker/
services:
  mariadb:
    env_file:
      - path: ./default.env
        required: true # default
      - path: /mnt/justsave/docker/env/mariadb/docker.env
        required: false
    labels:
      - com.centurylinklabs.watchtower.enable=false
    image: mariadb:11
    container_name: mariadb
    pull_policy: always
    volumes:
      - /mnt/justsave/docker/volume/mariadb/conf:/etc/mysql/conf.d
      - /mnt/justsave/docker/volume/mariadb/data:/var/lib/mysql
      - /mnt/justsave/docker/volume/mariadb/log:/var/log/mysql
      - /var/run/mysqld:/var/run/mysqld
      # healthcheck 小工具
      - ./my_mariadb_healthcheck.sh:/my_mariadb_healthcheck.sh:ro
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      # test: ["CMD-SHELL", "mariadb-admin ping --socket=/run/mysqld/mysqld.sock -u healthcheck"]
      test: [CMD-SHELL, /my_mariadb_healthcheck.sh]
      start_period: 180s
      start_interval: 2s
      timeout: 3s
      retries: 200
    logging:
      options:
        max-size: 4m
    hostname: docker-mariadb
    network_mode: bridge
    ports:
      - 0.0.0.0:3306:3306
      - 0.0.0.0:3306:3306/udp
    restart: unless-stopped
