services:
  wireguard:
    env_file:
      - path: /mnt/justsave/docker/compose/global_default.env
        required: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    image: wireguard
    container_name: wireguard
    pull_policy: build
    build:
      context: ./
      additional_contexts:
        resources: /mnt/justsave/docker/compose/build_resource
      pull: true
      dockerfile: ./wireguard.Dockerfile
    devices:
      - /dev/net/tun:/dev/net/tun:rwm
    volumes:
      - /mnt/justsave/docker/volume/wireguard/default/etc/wireguard:/etc/wireguard
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    logging:
      options:
        max-size: 4m
    extra_hosts:
      - host.docker.internal:host-gateway
    network_mode: bridge
    restart: always
